[package]
name = "realtime_terminal_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"
line_drawing = "*"
num = "0.4"
more-asserts = "0.2"